
package ajsserver;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Ajs_Exception", targetNamespace = "http://AJSServer/")
public class AjsException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AjsException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AjsException_Exception(String message, AjsException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AjsException_Exception(String message, AjsException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ajsserver.AjsException
     */
    public AjsException getFaultInfo() {
        return faultInfo;
    }

}
