
package ajsserver;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AjsService", targetNamespace = "http://AJSServer/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AjsService {


    /**
     * 
     * @param nazov
     * @return
     *     returns java.lang.String
     * @throws AjsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pridajPredmet", targetNamespace = "http://AJSServer/", className = "ajsserver.PridajPredmet")
    @ResponseWrapper(localName = "pridajPredmetResponse", targetNamespace = "http://AJSServer/", className = "ajsserver.PridajPredmetResponse")
    @Action(input = "http://AJSServer/AjsService/pridajPredmetRequest", output = "http://AJSServer/AjsService/pridajPredmetResponse", fault = {
        @FaultAction(className = AjsException_Exception.class, value = "http://AJSServer/AjsService/pridajPredmet/Fault/Ajs_Exception")
    })
    public String pridajPredmet(
        @WebParam(name = "nazov", targetNamespace = "")
        String nazov)
        throws AjsException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<ajsserver.Predmet>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPredmety", targetNamespace = "http://AJSServer/", className = "ajsserver.GetPredmety")
    @ResponseWrapper(localName = "getPredmetyResponse", targetNamespace = "http://AJSServer/", className = "ajsserver.GetPredmetyResponse")
    @Action(input = "http://AJSServer/AjsService/getPredmetyRequest", output = "http://AJSServer/AjsService/getPredmetyResponse")
    public List<Predmet> getPredmety();

    /**
     * 
     * @param priezvisko
     * @param meno
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pridajUcastnika", targetNamespace = "http://AJSServer/", className = "ajsserver.PridajUcastnika")
    @ResponseWrapper(localName = "pridajUcastnikaResponse", targetNamespace = "http://AJSServer/", className = "ajsserver.PridajUcastnikaResponse")
    @Action(input = "http://AJSServer/AjsService/pridajUcastnikaRequest", output = "http://AJSServer/AjsService/pridajUcastnikaResponse")
    public String pridajUcastnika(
        @WebParam(name = "meno", targetNamespace = "")
        String meno,
        @WebParam(name = "priezvisko", targetNamespace = "")
        String priezvisko);

    /**
     * 
     * @param nazov
     * @throws AjsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "vymazPredmet", targetNamespace = "http://AJSServer/", className = "ajsserver.VymazPredmet")
    @ResponseWrapper(localName = "vymazPredmetResponse", targetNamespace = "http://AJSServer/", className = "ajsserver.VymazPredmetResponse")
    @Action(input = "http://AJSServer/AjsService/vymazPredmetRequest", output = "http://AJSServer/AjsService/vymazPredmetResponse", fault = {
        @FaultAction(className = AjsException_Exception.class, value = "http://AJSServer/AjsService/vymazPredmet/Fault/Ajs_Exception")
    })
    public void vymazPredmet(
        @WebParam(name = "nazov", targetNamespace = "")
        String nazov)
        throws AjsException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<ajsserver.Ucastnik>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUcastnikov", targetNamespace = "http://AJSServer/", className = "ajsserver.GetUcastnikov")
    @ResponseWrapper(localName = "getUcastnikovResponse", targetNamespace = "http://AJSServer/", className = "ajsserver.GetUcastnikovResponse")
    @Action(input = "http://AJSServer/AjsService/getUcastnikovRequest", output = "http://AJSServer/AjsService/getUcastnikovResponse")
    public List<Ucastnik> getUcastnikov();

    /**
     * 
     * @param priezvisko
     * @param meno
     * @param uuid
     * @throws AjsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "vymazUcastnika", targetNamespace = "http://AJSServer/", className = "ajsserver.VymazUcastnika")
    @ResponseWrapper(localName = "vymazUcastnikaResponse", targetNamespace = "http://AJSServer/", className = "ajsserver.VymazUcastnikaResponse")
    @Action(input = "http://AJSServer/AjsService/vymazUcastnikaRequest", output = "http://AJSServer/AjsService/vymazUcastnikaResponse", fault = {
        @FaultAction(className = AjsException_Exception.class, value = "http://AJSServer/AjsService/vymazUcastnika/Fault/Ajs_Exception")
    })
    public void vymazUcastnika(
        @WebParam(name = "uuid", targetNamespace = "")
        String uuid,
        @WebParam(name = "meno", targetNamespace = "")
        String meno,
        @WebParam(name = "priezvisko", targetNamespace = "")
        String priezvisko)
        throws AjsException_Exception
    ;

    /**
     * 
     * @param uuid
     * @return
     *     returns java.util.List<ajsserver.PrezencnaListina>
     * @throws AjsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPrezencneListinyUcastnika", targetNamespace = "http://AJSServer/", className = "ajsserver.GetPrezencneListinyUcastnika")
    @ResponseWrapper(localName = "getPrezencneListinyUcastnikaResponse", targetNamespace = "http://AJSServer/", className = "ajsserver.GetPrezencneListinyUcastnikaResponse")
    @Action(input = "http://AJSServer/AjsService/getPrezencneListinyUcastnikaRequest", output = "http://AJSServer/AjsService/getPrezencneListinyUcastnikaResponse", fault = {
        @FaultAction(className = AjsException_Exception.class, value = "http://AJSServer/AjsService/getPrezencneListinyUcastnika/Fault/Ajs_Exception")
    })
    public List<PrezencnaListina> getPrezencneListinyUcastnika(
        @WebParam(name = "uuid", targetNamespace = "")
        String uuid)
        throws AjsException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws AjsException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "vymazPrezencnuListinu", targetNamespace = "http://AJSServer/", className = "ajsserver.VymazPrezencnuListinu")
    @ResponseWrapper(localName = "vymazPrezencnuListinuResponse", targetNamespace = "http://AJSServer/", className = "ajsserver.VymazPrezencnuListinuResponse")
    @Action(input = "http://AJSServer/AjsService/vymazPrezencnuListinuRequest", output = "http://AJSServer/AjsService/vymazPrezencnuListinuResponse", fault = {
        @FaultAction(className = AjsException_Exception.class, value = "http://AJSServer/AjsService/vymazPrezencnuListinu/Fault/Ajs_Exception")
    })
    public void vymazPrezencnuListinu(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws AjsException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<ajsserver.PrezencnaListina>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPrezencneListiny", targetNamespace = "http://AJSServer/", className = "ajsserver.GetPrezencneListiny")
    @ResponseWrapper(localName = "getPrezencneListinyResponse", targetNamespace = "http://AJSServer/", className = "ajsserver.GetPrezencneListinyResponse")
    @Action(input = "http://AJSServer/AjsService/getPrezencneListinyRequest", output = "http://AJSServer/AjsService/getPrezencneListinyResponse")
    public List<PrezencnaListina> getPrezencneListiny();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws AjsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getZoznamUcastnikov", targetNamespace = "http://AJSServer/", className = "ajsserver.GetZoznamUcastnikov")
    @ResponseWrapper(localName = "getZoznamUcastnikovResponse", targetNamespace = "http://AJSServer/", className = "ajsserver.GetZoznamUcastnikovResponse")
    @Action(input = "http://AJSServer/AjsService/getZoznamUcastnikovRequest", output = "http://AJSServer/AjsService/getZoznamUcastnikovResponse", fault = {
        @FaultAction(className = AjsException_Exception.class, value = "http://AJSServer/AjsService/getZoznamUcastnikov/Fault/Ajs_Exception")
    })
    public List<String> getZoznamUcastnikov(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws AjsException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws AjsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pridajPrezencnuListinu", targetNamespace = "http://AJSServer/", className = "ajsserver.PridajPrezencnuListinu")
    @ResponseWrapper(localName = "pridajPrezencnuListinuResponse", targetNamespace = "http://AJSServer/", className = "ajsserver.PridajPrezencnuListinuResponse")
    @Action(input = "http://AJSServer/AjsService/pridajPrezencnuListinuRequest", output = "http://AJSServer/AjsService/pridajPrezencnuListinuResponse", fault = {
        @FaultAction(className = AjsException_Exception.class, value = "http://AJSServer/AjsService/pridajPrezencnuListinu/Fault/Ajs_Exception")
    })
    public String pridajPrezencnuListinu(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<Ucastnik> arg2)
        throws AjsException_Exception
    ;

}
