
package ajsserver;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AjsServiceService", targetNamespace = "http://AJSServer/", wsdlLocation = "http://localhost:8888/ajs?wsdl")
public class AjsServiceService
    extends Service
{

    private final static URL AJSSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException AJSSERVICESERVICE_EXCEPTION;
    private final static QName AJSSERVICESERVICE_QNAME = new QName("http://AJSServer/", "AjsServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/ajs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AJSSERVICESERVICE_WSDL_LOCATION = url;
        AJSSERVICESERVICE_EXCEPTION = e;
    }

    public AjsServiceService() {
        super(__getWsdlLocation(), AJSSERVICESERVICE_QNAME);
    }

    public AjsServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AJSSERVICESERVICE_QNAME, features);
    }

    public AjsServiceService(URL wsdlLocation) {
        super(wsdlLocation, AJSSERVICESERVICE_QNAME);
    }

    public AjsServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AJSSERVICESERVICE_QNAME, features);
    }

    public AjsServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AjsServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AjsService
     */
    @WebEndpoint(name = "AjsServicePort")
    public AjsService getAjsServicePort() {
        return super.getPort(new QName("http://AJSServer/", "AjsServicePort"), AjsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AjsService
     */
    @WebEndpoint(name = "AjsServicePort")
    public AjsService getAjsServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://AJSServer/", "AjsServicePort"), AjsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AJSSERVICESERVICE_EXCEPTION!= null) {
            throw AJSSERVICESERVICE_EXCEPTION;
        }
        return AJSSERVICESERVICE_WSDL_LOCATION;
    }

}
